#include "src/Fire/fire_build.h"
#define ArrCount(X) sizeof(X)/sizeof(X[0])

static void AddVulkanSDK(BUILD_Project* p, const char* vk_sdk) {
	BUILD_AddIncludeDir(p, BUILD_Concat2(vk_sdk, "/Include"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/vulkan-1.lib"));
	
	// If compiling with the GLSLang shader compiler, the following are required
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/GenericCodeGen.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/glslang.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/MachineIndependent.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/OGLCompiler.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/OSDependent.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/SPIRV.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/SPIRV-Tools.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/SPIRV-Tools-diff.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/SPIRV-Tools-link.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/SPIRV-Tools-lint.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/SPIRV-Tools-opt.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/SPIRV-Tools-reduce.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/SPIRV-Tools-shared.lib"));
	BUILD_AddLinkerInput(p, BUILD_Concat2(vk_sdk, "/Lib/glslang-default-resource-limits.lib"));
}

int main() {
	const char* vk_sdk = getenv("VULKAN_SDK");
	if (vk_sdk == NULL) {
		printf("ERROR: Vulkan SDK not found (\"VULKAN_SDK\" environment variable is missing).\n");
		return 0;
	}
	
	const bool release_build = false;
	
	BUILD_ProjectOptions opts = {
		.debug_info = !release_build,
		.enable_optimizations = release_build,
		.c_runtime_library_dll = true, // glslang.lib uses /MD
	};
	
	// ---------------------------------------------------------
	
	BUILD_Project triangle;
	BUILD_ProjectInit(&triangle, "triangle", &opts);
	BUILD_AddIncludeDir(&triangle, "../"); // repository root dir
	
	BUILD_AddSourceFile(&triangle, "../src/demo_triangle/triangle.cpp");
	
	AddVulkanSDK(&triangle, vk_sdk);
	
	// Uncomment the following to enable vulkan validation layers
	BUILD_AddDefine(&triangle, "GPU_ENABLE_VALIDATION");
	
	BUILD_AddSourceFile(&triangle, "../src/gpu/gpu_vulkan.c");
	BUILD_AddLinkerInput(&triangle, "User32.lib"); // required for gpu_vulkan.c (imp_GetWindowLongPtrW)
	
	// ---------------------------------------------------------
	
	BUILD_Project pbr_renderer;
	BUILD_ProjectInit(&pbr_renderer, "pbr_renderer", &opts);
	BUILD_AddIncludeDir(&pbr_renderer, "../"); // repository root dir
	BUILD_AddIncludeDir(&pbr_renderer, "../third_party"); // required for including <assimp/..>
	
	BUILD_AddSourceFile(&pbr_renderer, "../src/demo_pbr_renderer/main.cpp");
	BUILD_AddSourceFile(&pbr_renderer, "../src/demo_pbr_renderer/common.cpp");
	BUILD_AddSourceFile(&pbr_renderer, "../src/demo_pbr_renderer/os_utils.cpp");
	BUILD_AddSourceFile(&pbr_renderer, "../src/demo_pbr_renderer/render.cpp");
	BUILD_AddSourceFile(&pbr_renderer, "../src/demo_pbr_renderer/asset_import.cpp");
	
	AddVulkanSDK(&pbr_renderer, vk_sdk);
	
	// Uncomment the following to enable vulkan validation layers
	BUILD_AddDefine(&pbr_renderer, "GPU_ENABLE_VALIDATION");
	
	BUILD_AddSourceFile(&pbr_renderer, "../src/gpu/gpu_vulkan.c");
	BUILD_AddLinkerInput(&pbr_renderer, "User32.lib"); // required for gpu_vulkan.c (imp_GetWindowLongPtrW)
	
	// include assimp
	BUILD_AddLinkerInput(&pbr_renderer, "../third_party/assimp/lib/assimp-vc143-mt.lib");
	BUILD_AddExtraCompilerArg(&pbr_renderer, "/wd\"4251\""); // disable a warning generated by Assimp
	
	// ---------------------------------------------------------
	
	BUILD_Project* projects[] = {&triangle, &pbr_renderer};
	BUILD_CreateDirectory("build");
	
	// Copy Assimp dll to the build directory
	BUILD_CopyFile("third_party/assimp/lib/assimp-vc143-mt.dll", "build/assimp-vc143-mt.dll");
	
	bool ok = BUILD_CreateVisualStudioSolution("build", ".", "demos.sln", projects, ArrCount(projects), BUILD_GetConsole());
	
	if (ok) {
		printf("Project files were generated successfully! See the \"build\" folder.\n");
	} else {
		printf("ERROR: failed to generate project files.\n");
	}
	
	return 0;
}
